### ISSUE TITLE
upgrade to 2.6.1 from 2.3.1

### ISSUE THREAD

**Issue by randysecrist** [klarna/erlavro#70]
Hey there ...

Using version 2.3.1 - decoding schema was working nicely.  After upgrade however it fails for some default values for primitives (such as long) which specify null in a union.

Trace:
```
** (ErlangError) Erlang error: {:bad_default, [record: "MyCrappySchema", field: "someLongTypeField", reason: :function_clause]}
    (erlavro) src/avro_json_decoder.erl:368: :avro_json_decoder.parse_prim(:null, {:avro_primitive_type, "long", []})
    (erlavro) src/avro_json_decoder.erl:334: anonymous fn/3 in :avro_json_decoder.parse/5
    (erlavro) src/avro_record.erl:220: :avro_record.do_default/4
    (erlavro) src/avro_record.erl:169: anonymous fn/3 in :avro_record.parse_defaults/2
    (stdlib) lists.erl:1239: :lists.map/2
    (stdlib) lists.erl:1239: :lists.map/2
    (erlavro) src/avro_record.erl:177: :avro_record.parse_defaults/2
    (erlavro) src/avro_schema_store.erl:236: :avro_schema_store.import_schema_json/3
```

I reviewed the versions between 2.3.1 and see some handling of default values changed.  I see there is a ```ignore_bad_default_values``` option when using ```decode_schema```; however I don't call that directly.

I make a schema store using this fun:

```
    store = :avro_schema_store
      .import_schema_json(schema_json, :avro_schema_store.new([]))
    :avro.make_decoder(store, [])
```

Then use the decoder to deserialize messages.  GIven this usage pattern, where is the best place to pass the ```ignore_bad_default_values``` option;  or if there is another way ; what is it?

**Comment by zmstone** [comment]
Hi @randysecrist 

Default values in the old versions were decoded but not validated.
a non-strict option (`ignore_bad_default_values`) was added when strict validation was added.

If `someLongTypeField` field is a `long` type but default value is given as `null` or `"null"`,
then it's violating the spec, I'll see if it's possible to tolerate it without breaking too much.

Workarounds before we can fix the code.
If in your use case, there is always one type per-store, you can avoid using schema store:
```
{:ok, json} = :file.read_file('path/to/json')
type = :avro.decode_schema(json, [ignore_bad_default_values])
:avro.make_simple_decoder(type, [])
```

otherwise a slightly more complex one:
call `:avro.decode_schema/2` with option `ignore_bad_default_values`.
then call `:avro_schema_store.new/1` to create a store,
finally `:avro_schema_store.add_type/2` to add type and make decoder from it.

**Comment by zmstone** [comment]
simple decoder takes only one arg (binary) to decode not two (type name and binary).

and this (not tested) should work for the regular (not 'simple') decoder:
```
  defp make_decoder(schema_json) when is_binary(schema_json) do
    avro_schema = :avro.decode_schema(schema_json, [{:ignore_bad_default_values, true}])
    store = :avro_schema_store.new([]),
    store = :avro_schema_store.add_type(type, store)
    :avro.make_decoder(store, [])
  end
```

**Comment by randysecrist** [comment]
Tested that code; it works under 2.6.1.  Thanks @zmstone!
